### ISSUE TITLE
Update ReadMe file with essentials

### ISSUE THREAD

**Issue by sarthakjdev** [sarthakjdev/create-express-ts-api#1]
Here are the essentials to be added to the readme file: 

- [x] Information about the package. 
- [x] Installation guide
- [x] Contributors guidelines
- [x] Author Details
- [x] License section
- [x] Reference of [this](https://blog.sarthakjdev.com/develop-rest-apis) blog for reference

**Comment by Anubhavdevv** [comment]
Hey @sarthakjdev I would like to work on this issue 
It would be great if you could assign this to me! 

Thank you!

**Comment by sarthakjdev** [comment]
Hey @Anubhavdevv 
Thanks for showing up your interest. 
Do let me know if you need any help.
Regards

**Comment by Anubhavdevv** [comment]
Sure
