### ISSUE TITLE
Add issue and pull request template.

### ISSUE THREAD

**Issue by sarthakjdev** [sarthakjdev/create-express-ts-api#5]
Add issue and pull request template for more structured issues and PR creation.

For reference visit [here](https://github.com/sarthakjdev/create-express-ts-api/tree/main/starter-kit/.github)

**Comment by Anubhavdevv** [comment]
I would like to work on this! Issue!
Could you assign this issue to me!

**Comment by sarthakjdev** [comment]
ya sure !!
